window.FANMA_FACEBOOK_PAGE =
  "https://www.facebook.com/p/%E6%B1%8E%E9%A6%AC%E6%95%B4%E5%90%88%E8%A1%8C%E9%8A%B7-61558782960194/";

window.FANMA_CATEGORIES = [
  "全部",
  "演唱會案例",
  "記者會",
  "Team Building",
  "公司活動",
  "春酒尾牙",
  "品牌活動",
  "開幕活動",
  "政府協會活動",
  "展覽市集",
];

window.FANMA_CASES = [
  {
    slug: "2026-anti-drug-education-exhibition",
    published: true,
    title: "花蓮反毒教育特展｜解癮－解開毒品上癮的真相",
    category: "展覽市集",
    clientLabel: "相關單位",
    client: "教育部／中國信託反毒教育基金會／教育部花蓮聯絡處",
    location: "花蓮縣",
    people: "參觀人次待補",
    status: "已完成・結案案例",
    services: ["專案企劃", "活動設計", "人力策略", "展覽執行"],
    summary: "汎馬完成 115 年度花蓮「解癮－解開毒品上癮的真相」反毒教育特展，從專案企劃、活動設計到人力策略統籌，以大型展覽經驗協助正確觀念被看見。",
    storyTitle: "用專業跨界，打造深具意義的反毒教育特展",
    story: [
      "汎馬整合行銷的專案經驗不僅獲得企業客戶肯定，也持續參與公部門與教育推廣專案。本案為 115 年度花蓮「解癮－解開毒品上癮的真相」2026 反毒教育特展結案紀錄。",
      "這不只是一場展覽，更是傳遞正確價值觀、發揮社會影響力的重要任務。從專案企劃、活動設計到人力策略統籌，我們將過往執行大型展覽活動的經驗投入本次特展，並完成各項現場執行工作。",
      "無論是企業活動或公共議題特展，汎馬都以一致的專業標準整合執行細節，讓每一場活動不只順利完成，也能清楚傳達它所承載的意義。",
    ],
    highlights: [
      "以反毒教育為核心，兼顧知識傳遞與公共影響力",
      "整合專案企劃、活動設計及現場執行",
      "依展覽需求規劃人力配置與工作策略",
      "運用大型展覽經驗，建立完整的執行架構",
    ],
    tags: ["教育部", "中國信託反毒教育基金會", "教育部花蓮聯絡處", "跨界行銷", "展覽活動"],
    image: "assets/images/exhibition-space.jpg",
    imageIsPlaceholder: true,
    imageNote: "目前使用商用範例圖片，待汎馬提供本案活動照片後替換。",
    sourceLabel: "汎馬提供之 Facebook 貼文內容",
    facebook: "#",
  },
  {
    slug: "company-a-year-end-party",
    title: "企業A 年度春酒尾牙活動",
    category: "春酒尾牙",
    client: "企業A",
    location: "台北市",
    people: "約 300 人",
    services: ["活動企劃", "舞台硬體", "視覺設計", "影像紀錄"],
    summary: "年度春酒尾牙活動整合主題規劃、舞台燈光、抽獎流程與活動紀錄，協助企業打造有記憶點的員工晚宴。",
    highlights: ["年度晚宴流程規劃", "舞台與燈光音響配置", "抽獎與表演橋段安排", "活動攝影與精華素材"],
    image: "assets/images/corporate.jpg",
    facebook: "#",
  },
  {
    slug: "brand-b-launch-event",
    title: "品牌B 新品發表記者會",
    category: "記者會",
    client: "品牌B",
    location: "新北市",
    people: "約 120 人",
    services: ["活動企劃", "媒體動線", "主視覺設計", "攝影紀錄"],
    summary: "新品發表記者會整合媒體邀請、主持流程、拍照背板與品牌曝光素材，讓產品亮點在現場被清楚看見。",
    highlights: ["媒體報到與動線規劃", "發表流程與主持 cue 點", "品牌背板與拍照區", "活動後素材整理"],
    image: "assets/images/press.jpg",
    facebook: "#",
  },
  {
    slug: "unit-c-opening-ceremony",
    title: "單位C 開幕剪綵典禮",
    category: "開幕活動",
    client: "單位C",
    location: "桃園市",
    people: "約 180 人",
    services: ["儀式流程", "硬體統籌", "會場佈置", "平面攝影"],
    summary: "開幕剪綵典禮安排啟用儀式、貴賓接待、舞台背板與現場動線，讓重要時刻順利完成。",
    highlights: ["剪綵儀式設計", "貴賓接待與流程控管", "拍照區與活動背板", "現場紀錄與社群素材"],
    image: "assets/images/opening.jpg",
    facebook: "#",
  },
  {
    slug: "company-d-family-day",
    title: "企業D Team Building 團隊活動",
    category: "Team Building",
    client: "企業D",
    location: "台中市",
    people: "約 500 人",
    services: ["活動企劃", "闖關設計", "帳篷硬體", "攝影紀錄"],
    summary: "Team Building 團隊活動結合闖關、戶外動線、舞台表演、帳篷硬體與現場安全規劃，提升員工參與感。",
    highlights: ["親子闖關活動設計", "戶外動線與雨備規劃", "帳篷桌椅與舞台設備", "活動照片與短影音素材"],
    image: "assets/images/team-building.jpg",
    facebook: "#",
  },
  {
    slug: "association-e-annual-meeting",
    title: "協會E 年度會員大會",
    category: "政府協會活動",
    client: "協會E",
    location: "台北市",
    people: "約 220 人",
    services: ["流程規劃", "報到系統", "舞台硬體", "影像紀錄"],
    summary: "會員大會與論壇活動整合議程、報到、舞台與影像紀錄，協助協會與單位維持活動節奏。",
    highlights: ["議程與貴賓流程安排", "報到與座位規劃", "舞台視訊與收音", "活動紀錄與資料整理"],
    image: "assets/images/conference.jpg",
    facebook: "#",
  },
  {
    slug: "restaurant-f-brand-event",
    title: "餐飲品牌F 品牌推廣活動",
    category: "品牌活動",
    client: "餐飲品牌F",
    location: "台北市",
    people: "約 80 人",
    services: ["品牌企劃", "場景佈置", "體驗流程", "社群素材"],
    summary: "品牌推廣活動規劃產品體驗、快閃互動、KOL 拍照佈置與社群素材，延伸現場曝光效益。",
    highlights: ["品牌體驗流程", "拍照場景與陳列", "互動橋段設計", "活動後社群內容"],
    image: "assets/images/brand.jpg",
    facebook: "#",
  },
  {
    slug: "tech-g-awards",
    title: "科技公司G 業務表揚大會",
    category: "公司活動",
    client: "科技公司G",
    location: "新竹市",
    people: "約 260 人",
    services: ["頒獎流程", "舞台硬體", "簡報視訊", "平面攝影"],
    summary: "業務表揚大會整合頒獎流程、長官致詞、團隊合影與活動回顧，讓企業榮耀時刻被完整呈現。",
    highlights: ["頒獎流程與獎項安排", "舞台視訊與簡報播放", "團隊合影與拍照動線", "活動紀錄素材"],
    image: "assets/images/planning.jpg",
    facebook: "#",
  },
  {
    slug: "company-h-anniversary",
    title: "單位H 戶外演唱會活動",
    category: "演唱會案例",
    client: "企業H",
    location: "高雄市",
    people: "約 400 人",
    services: ["節目流程", "舞台硬體", "燈光音響", "影像紀錄"],
    summary: "戶外演唱會活動整合舞台搭設、燈光音響、演出流程、貴賓區與活動紀錄，兼顧氣氛與現場秩序。",
    highlights: ["演出流程與節目 cue 點", "舞台燈光音響配置", "觀眾動線與貴賓區", "活動後精華影像素材"],
    image: "assets/images/concert.jpg",
    facebook: "#",
  },
  {
    slug: "brand-i-pop-up",
    title: "品牌I 快閃體驗活動",
    category: "展覽市集",
    client: "品牌I",
    location: "台北市",
    people: "不定時段入場",
    services: ["空間規劃", "互動設計", "展示物製作", "社群紀錄"],
    summary: "快閃與展覽市集活動規劃攤位、體驗區、品牌展示與現場導購內容，讓來賓更容易停留互動。",
    highlights: ["展區動線與排隊規劃", "互動體驗流程", "展示物與輸出製作", "社群素材紀錄"],
    image: "assets/images/exhibition.jpg",
    facebook: "#",
  },
  {
    slug: "unit-j-government-event",
    title: "單位J 地方宣導活動",
    category: "政府協會活動",
    client: "單位J",
    location: "基隆市",
    people: "約 350 人",
    services: ["活動企劃", "帳篷硬體", "舞台音響", "活動紀錄"],
    summary: "地方宣導活動整合舞台節目、宣導攤位、帳篷硬體與民眾互動，協助訊息有效傳達。",
    highlights: ["舞台活動與民眾互動", "戶外硬體與帳篷配置", "現場安全與動線", "活動紀錄素材"],
    image: "assets/images/conference.jpg",
    facebook: "#",
  },
  {
    slug: "company-k-sports-day",
    title: "企業K 員工運動會",
    category: "Team Building",
    client: "企業K",
    location: "新北市",
    people: "約 600 人",
    services: ["活動企劃", "競賽設計", "硬體統籌", "攝影紀錄"],
    summary: "員工運動會整合競賽分組、隊呼、場地動線、帳篷補給與活動紀錄，讓大型戶外活動更有秩序。",
    highlights: ["競賽流程與分組設計", "場地動線與補給區", "舞台與音響配置", "空拍與活動紀錄"],
    image: "assets/images/sports-day.jpg",
    facebook: "#",
  },
  {
    slug: "brand-l-media-party",
    title: "品牌L 媒體體驗派對",
    category: "品牌活動",
    client: "品牌L",
    location: "台北市",
    people: "約 150 人",
    services: ["品牌企劃", "視覺設計", "活動攝影", "社群素材"],
    summary: "媒體體驗派對規劃品牌場景、KOL 拍照、媒體動線與活動後宣傳內容，提升品牌互動與曝光。",
    highlights: ["媒體與 KOL 動線", "品牌場景與拍照點", "產品體驗橋段", "活動後圖文素材"],
    image: "assets/images/media-party.jpg",
    facebook: "#",
  },
];

window.FANMA_CASES = window.FANMA_CASES.map((item) => ({
  ...item,
  sourceLabel: item.sourceLabel || "汎馬 Facebook 粉專活動紀錄",
  sourceUrl: item.facebook === "#" ? window.FANMA_FACEBOOK_PAGE : item.facebook,
}));
