window.FANMA_CATEGORIES = [
  "全部",
  "春酒尾牙",
  "企業活動",
  "品牌活動",
  "開幕活動",
  "家庭日",
  "發表記者會",
  "政府協會活動",
  "展覽市集",
];

window.FANMA_CASES = [
  {
    slug: "company-a-year-end-party",
    title: "企業A 年度春酒尾牙活動",
    category: "春酒尾牙",
    client: "企業A",
    location: "台北市",
    people: "約 300 人",
    services: ["活動企劃", "舞台硬體", "視覺設計", "影像紀錄"],
    summary: "此案例先作為尾牙活動模板，保留主題規劃、舞台燈光、抽獎流程與活動紀錄欄位，後續可替換為真實客戶內容。",
    highlights: ["年度晚宴流程規劃", "舞台與燈光音響配置", "抽獎與表演橋段安排", "活動攝影與精華素材"],
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "brand-b-launch-event",
    title: "品牌B 新品發表記者會",
    category: "發表記者會",
    client: "品牌B",
    location: "新北市",
    people: "約 120 人",
    services: ["活動企劃", "媒體動線", "主視覺設計", "攝影紀錄"],
    summary: "此模板適合放置新品發表、媒體邀請、主持流程、拍照背板與品牌曝光素材。",
    highlights: ["媒體報到與動線規劃", "發表流程與主持 cue 點", "品牌背板與拍照區", "活動後素材整理"],
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "unit-c-opening-ceremony",
    title: "單位C 開幕剪綵典禮",
    category: "開幕活動",
    client: "單位C",
    location: "桃園市",
    people: "約 180 人",
    services: ["儀式流程", "硬體統籌", "會場佈置", "平面攝影"],
    summary: "開幕活動模板可放置剪綵、啟用儀式、貴賓接待、舞台背板與現場動線內容。",
    highlights: ["剪綵儀式設計", "貴賓接待與流程控管", "拍照區與活動背板", "現場紀錄與社群素材"],
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "company-d-family-day",
    title: "企業D 親子家庭日活動",
    category: "家庭日",
    client: "企業D",
    location: "台中市",
    people: "約 500 人",
    services: ["活動企劃", "闖關設計", "帳篷硬體", "攝影紀錄"],
    summary: "家庭日模板可承接親子闖關、戶外動線、舞台表演、帳篷與現場安全規劃。",
    highlights: ["親子闖關活動設計", "戶外動線與雨備規劃", "帳篷桌椅與舞台設備", "活動照片與短影音素材"],
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "association-e-annual-meeting",
    title: "協會E 年度會員大會",
    category: "政府協會活動",
    client: "協會E",
    location: "台北市",
    people: "約 220 人",
    services: ["流程規劃", "報到系統", "舞台硬體", "影像紀錄"],
    summary: "此模板可用於會員大會、論壇、頒獎或協會型活動，保留議程、報到與舞台欄位。",
    highlights: ["議程與貴賓流程安排", "報到與座位規劃", "舞台視訊與收音", "活動紀錄與資料整理"],
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "restaurant-f-brand-event",
    title: "餐飲品牌F 品牌推廣活動",
    category: "品牌活動",
    client: "餐飲品牌F",
    location: "台北市",
    people: "約 80 人",
    services: ["品牌企劃", "場景佈置", "體驗流程", "社群素材"],
    summary: "品牌活動模板可放產品體驗、快閃活動、KOL 互動、拍照佈置與社群素材。",
    highlights: ["品牌體驗流程", "拍照場景與陳列", "互動橋段設計", "活動後社群內容"],
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "tech-g-awards",
    title: "科技公司G 業務表揚大會",
    category: "企業活動",
    client: "科技公司G",
    location: "新竹市",
    people: "約 260 人",
    services: ["頒獎流程", "舞台硬體", "簡報視訊", "平面攝影"],
    summary: "企業表揚模板可放頒獎、業務表揚、長官致詞、團隊合影與活動回顧。",
    highlights: ["頒獎流程與獎項安排", "舞台視訊與簡報播放", "團隊合影與拍照動線", "活動紀錄素材"],
    image: "https://images.unsplash.com/photo-1515168833906-d2a3b82b1a48?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "company-h-anniversary",
    title: "企業H 週年慶活動",
    category: "企業活動",
    client: "企業H",
    location: "高雄市",
    people: "約 400 人",
    services: ["主題企劃", "會場佈置", "舞台硬體", "精華影片"],
    summary: "週年慶模板可承接企業里程碑、品牌回顧、長官致詞、員工互動與精華影片。",
    highlights: ["週年主題與流程設計", "企業歷程視覺牆", "舞台表演與致詞流程", "活動後精華影片"],
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "brand-i-pop-up",
    title: "品牌I 快閃體驗活動",
    category: "展覽市集",
    client: "品牌I",
    location: "台北市",
    people: "不定時段入場",
    services: ["空間規劃", "互動設計", "展示物製作", "社群紀錄"],
    summary: "展覽市集模板可放快閃、攤位、體驗區、品牌展示與現場導購內容。",
    highlights: ["展區動線與排隊規劃", "互動體驗流程", "展示物與輸出製作", "社群素材紀錄"],
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "unit-j-government-event",
    title: "單位J 地方宣導活動",
    category: "政府協會活動",
    client: "單位J",
    location: "基隆市",
    people: "約 350 人",
    services: ["活動企劃", "帳篷硬體", "舞台音響", "活動紀錄"],
    summary: "公部門與協會活動模板可承接地方活動、宣導攤位、舞台節目與民眾互動。",
    highlights: ["舞台活動與民眾互動", "戶外硬體與帳篷配置", "現場安全與動線", "活動紀錄素材"],
    image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "company-k-sports-day",
    title: "企業K 員工運動會",
    category: "家庭日",
    client: "企業K",
    location: "新北市",
    people: "約 600 人",
    services: ["活動企劃", "競賽設計", "硬體統籌", "攝影紀錄"],
    summary: "運動會模板可放競賽分組、隊呼、場地動線、帳篷補給與活動照片。",
    highlights: ["競賽流程與分組設計", "場地動線與補給區", "舞台與音響配置", "空拍與活動紀錄"],
    image: "https://images.unsplash.com/photo-1526676037777-05a232554f77?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
  {
    slug: "brand-l-media-party",
    title: "品牌L 媒體體驗派對",
    category: "品牌活動",
    client: "品牌L",
    location: "台北市",
    people: "約 150 人",
    services: ["品牌企劃", "視覺設計", "活動攝影", "社群素材"],
    summary: "媒體體驗派對模板可放品牌場景、KOL 拍照、媒體動線與活動後宣傳內容。",
    highlights: ["媒體與 KOL 動線", "品牌場景與拍照點", "產品體驗橋段", "活動後圖文素材"],
    image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&w=1200&q=80",
    facebook: "#",
  },
];
